### PR TITLE
Converted to an actual R package

### PR DESCRIPTION
**Pull request by Dasonk**
A long time ago I converted this to a package. I can't remember if I ever submitted a pull request but these commits never were merged in to your repo so I thought I'd try again.

### CODE REVIEW

**Comment by SiBorg7** [comment]
Thanks Dason!  Much appreciated.  I was thinking about this the other day interestingly enough.  I hope that you are well!

**Comment by Dasonk** [comment]
Do you think you'll accept the pull request or should we close it?

**Comment by SiBorg7** [comment]
Oh sorry, I didn't realise I needed to do anything...Will look in the next couple of daysOn 26 Apr 2017 20:02, Dason Kurkiewicz <notifications@github.com> wrote:Do you think you'll accept the pull request or should we close it?

**Review by SiBorg7 — APPROVED** [review]

**Comment by SiBorg7** [comment]
Hi Dason.  I think I've approved your changes, so have I done everything that was required?

BW

Simon

**Pull request merged**
